const cron = require('node-cron');
const mongoose = require('mongoose');
const autonomousScheduler = require('./autonomousScheduler');
const Trip = require('../models/Trip');
const Route = require('../models/Route');
const Bus = require('../models/Bus');
const { logger } = require('../src/core/logger');

/**
 * Automatic Schedule Generator
 * Runs daily at midnight to generate schedules for the next day/week/month
 */

// Generate and save trips to database
const generateAndSaveSchedules = async (scheduleType = 'daily') => {
  try {
    logger.info(`🔄 Starting automatic schedule generation: ${scheduleType}`);
    
    const result = await autonomousScheduler.generateAutomaticSchedule(scheduleType);
    
    if (!result.success || !result.schedules) {
      logger.error('Failed to generate schedules');
      return;
    }

    let savedCount = 0;
    let skippedCount = 0;

    for (const schedule of result.schedules) {
      try {
        // Check if trip already exists
        const existingTrip = await Trip.findOne({
          routeId: schedule.routeId,
          serviceDate: new Date(schedule.date),
          startTime: schedule.startTime,
          status: { $in: ['scheduled', 'active'] }
        });

        if (existingTrip) {
          skippedCount++;
          continue;
        }

        // Get route to get depot and fare info
        const route = await Route.findById(schedule.routeId).populate('depotId');
        if (!route) {
          skippedCount++;
          continue;
        }

        // Get bus to get capacity
        const bus = await Bus.findById(schedule.busId);
        if (!bus) {
          skippedCount++;
          continue;
        }

        // Create trip (store fatigue info in notes since schema doesn't have fatigue fields)
        const trip = new Trip({
          routeId: schedule.routeId,
          busId: schedule.busId,
          driverId: schedule.driverId,
          conductorId: schedule.conductorId,
          serviceDate: new Date(schedule.date),
          startTime: schedule.startTime,
          endTime: schedule.endTime,
          fare: route.baseFare || 100,
          capacity: bus.seatingCapacity || 50,
          availableSeats: bus.seatingCapacity || 50,
          bookedSeats: 0,
          status: 'scheduled',
          depotId: route.depotId?._id || route.depotId,
          notes: `Auto-generated. Driver Fatigue: ${schedule.driverFatigueScore || 0}, Conductor Fatigue: ${schedule.conductorFatigueScore || 0}`
        });

        await trip.save();
        savedCount++;
      } catch (error) {
        logger.error(`Error saving schedule for route ${schedule.routeName}:`, error);
        skippedCount++;
      }
    }

    logger.info(`✅ Schedule generation complete: ${savedCount} saved, ${skippedCount} skipped`);
  } catch (error) {
    logger.error('Error in automatic schedule generation:', error);
  }
};

// Schedule daily generation (runs at 12:00 AM every day)
const startDailyScheduler = () => {
  cron.schedule('0 0 * * *', async () => {
    logger.info('🕛 Daily schedule generation triggered');
    await generateAndSaveSchedules('daily');
  });
  logger.info('✅ Daily scheduler started (runs at 12:00 AM daily)');
};

// Schedule weekly generation (runs at 12:00 AM every Monday)
const startWeeklyScheduler = () => {
  cron.schedule('0 0 * * 1', async () => {
    logger.info('🕛 Weekly schedule generation triggered');
    await generateAndSaveSchedules('weekly');
  });
  logger.info('✅ Weekly scheduler started (runs at 12:00 AM every Monday)');
};

// Schedule monthly generation (runs at 12:00 AM on the 1st of each month)
const startMonthlyScheduler = () => {
  cron.schedule('0 0 1 * *', async () => {
    logger.info('🕛 Monthly schedule generation triggered');
    await generateAndSaveSchedules('monthly');
  });
  logger.info('✅ Monthly scheduler started (runs at 12:00 AM on 1st of each month)');
};

// Initialize all schedulers
const initializeSchedulers = () => {
  startDailyScheduler();
  startWeeklyScheduler();
  startMonthlyScheduler();
  
  // Also generate today's schedule immediately on startup if not exists
  setTimeout(async () => {
    try {
      const today = new Date().toISOString().split('T')[0];
      const todayTrips = await Trip.countDocuments({
        date: today,
        isAutoGenerated: true,
        status: 'scheduled'
      });
      
      if (todayTrips === 0) {
        logger.info('🔄 No schedules found for today, generating now...');
        await generateAndSaveSchedules('daily');
      }
    } catch (error) {
      logger.error('Error generating today\'s schedules:', error);
    }
  }, 5000); // Wait 5 seconds after server startup
};

module.exports = {
  initializeSchedulers,
  generateAndSaveSchedules,
  startDailyScheduler,
  startWeeklyScheduler,
  startMonthlyScheduler
};
