version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: yatrik-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: yatrik_erp
    networks:
      - yatrik-network

  # Backend API Server
  backend:
    build: ./backend
    container_name: yatrik-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/yatrik_erp?authSource=admin
      NODE_ENV: production
      JWT_SECRET: your-super-secure-jwt-secret-minimum-32-characters-long
      SESSION_SECRET: your-super-secure-session-secret-minimum-32-characters-long
      FRONTEND_URL: http://localhost:3000
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - yatrik-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: yatrik-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - yatrik-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: yatrik-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yatrik-network
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  yatrik-network:
    driver: bridge
